In [4]:
import numpy as np
y=np.array([1,2,3,4,5])
print(y)
print(type(y))
print(y.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [5]:
import numpy as np
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x.ndim)

2


In [8]:
l=[]

for i in range(1,5):
    num=int(input("likho number: "))
    l.append(num)

print(np.array(l))    

likho number: 1
likho number: 2
likho number: 3
likho number: 4
[1 2 3 4]


In [1]:
import numpy as np
x=np.array([1,2,3,4], ndmin=4)
print(x)

[[[[1 2 3 4]]]]


In [5]:
x=np.zeros(4)
print(x)
y=np.ones((2,3))
print(y)


[0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [7]:
x=np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
x=np.eye(3)
print(x)
print()
y=np.eye(3,5)
print(y)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [15]:
arr= np.linspace(1,10, num=19)
print(arr)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10. ]


In [17]:
x=np.random.rand(3)
print(x)
print()
y=np.random.rand(2,5)
print(y)

[0.98392954 0.90338355 0.3895413 ]

[[0.37280204 0.47762025 0.59214705 0.10574302 0.84188124]
 [0.80900266 0.71401842 0.58409097 0.77871905 0.25488286]]


In [19]:
x=np.random.randn(3)
print(x)

[-1.01276906e-03  1.28541176e+00 -2.22493596e-01]


In [20]:
x=np.random.randint(1,10,50)
print(x)

[2 6 3 2 6 6 7 2 2 4 1 5 1 1 5 8 1 7 3 9 8 1 8 8 3 9 5 8 7 8 1 8 3 4 6 7 7
 9 3 4 9 7 9 1 3 3 5 9 6 7]


In [26]:
arr=np.array([1,2,3,4])+10
print(arr)
print(arr-10)
print(arr/3)
print(arr%3)


[11 12 13 14]
[1 2 3 4]
[3.66666667 4.         4.33333333 4.66666667]
[2 0 1 2]


In [28]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(arr1+arr2)
arr3=np.add(arr1,arr2)
arr4=np.multiply(arr1,arr2)
print(arr3)
print(arr4)

[5 7 9]
[5 7 9]
[ 4 10 18]


In [30]:
import numpy as np
var = np.array([3,2,1,4,5,3,2])
print("min: ", np.min(var), np.argmin (var)) #argmin se min ki position pta chalti hai
print("max: ", np.max (var), np.argmax(var))
print("sqrt: ",np.sqrt(var))
print("sin: ", np.sin(var))
print("cumsum: ", np.cumsum(var)) #cumsum of ith element is sum till ith index

min:  1 2
max:  5 4
sqrt:  [1.73205081 1.41421356 1.         2.         2.23606798 1.73205081
 1.41421356]
sin:  [ 0.14112001  0.90929743  0.84147098 -0.7568025  -0.95892427  0.14112001
  0.90929743]
cumsum:  [ 3  5  6 10 15 18 20]


In [31]:
import numpy as np
var = np.array([[1,2,3,4],[1,2,3,4]])
print (var)
print ()
print(var.shape)

[[1 2 3 4]
 [1 2 3 4]]

(2, 4)


In [34]:
vari= np.array([1,2,3,4], ndmin=4)
print(vari)
print(vari.ndim)
print()
print (vari.shape) # no of rows from outer to inner

[[[[1 2 3 4]]]]
4

(1, 1, 1, 4)


In [36]:
var2 = np.array([1,2,3,4,5,6,1,2,3])
print(var2)
print(var2.ndim)
print()
x = var2.reshape (3,3)
print(x)
print(x.ndim)

[1 2 3 4 5 6 1 2 3]
1

[[1 2 3]
 [4 5 6]
 [1 2 3]]
2


In [40]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print (var3)
print(var3.ndim)
print()
x1 = var3.reshape (2,3,2)
print(x1)
print(x1.ndim)
x2=x1.reshape(-1) #reshape into 1d array
print(x2)
print(x2.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


In [41]:
import numpy as np
var = np.array([9,8,7,6])
#               0,1,2,3
#             -4,-3,-2,-1
print(var[1])
print(var[-3])

8
8


In [42]:
var1= np.array([[9,8,7], [4,5,6]])
print(var1)
print(vari.ndim)
print()
print(var1[0,1])

[[9 8 7]
 [4 5 6]]
4

8


In [44]:
import numpy as np
var = np.array([9,8,7,6,5,4,3])
0,1,2,3,4,5,6
print(var)
print()
print("2 to 5: ",var[1:5])
print(" 2 to End : ", var[1:])
print("start to 5: ",var[:5])
print("stop: ", var[::2])# 2 cha gap sodun print

[9 8 7 6 5 4 3]

2 to 5:  [8 7 6 5]
 2 to End :  [8 7 6 5 4 3]
start to 5:  [9 8 7 6 5]
stop:  [9 7 5 3]


In [46]:
vari = np.array([[1,2,3,4],[1,2,3,4]])
print(vari)
print ()

for j in vari:
    print(j)   # row wise print

print()

for k in vari:
    for l in k:
        print(l)  #print as single entity

[[1 2 3 4]
 [1 2 3 4]]

[1 2 3 4]
[1 2 3 4]

1
2
3
4
1
2
3
4


In [49]:
var3 = np.array([[19,8,7,6],[1,2,3,4]])
print(var3)
print(var3.ndim)
print()
for i in np.nditer (var3):
     print(i)

[[19  8  7  6]
 [ 1  2  3  4]]
2

19
8
7
6
1
2
3
4


In [50]:
var3 = np.array([[[9,8,7,6],[1,2,3,4]]])
print(var3)
print(var3.ndim)
print()
for i,d in np.ndenumerate(var3):
     print (i, d)

[[[9 8 7 6]
  [1 2 3 4]]]
3

(0, 0, 0) 9
(0, 0, 1) 8
(0, 0, 2) 7
(0, 0, 3) 6
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4


In [53]:
import numpy as np
var = np.array([1,2,3,4])
co =var.copy()
var[1]=40
print("var: ",var) 
print("copy : ",co) #change reflect nahi honar
vi = var.view()
print("view",vi) #change reflect honar

var:  [ 1 40  3  4]
copy :  [1 2 3 4]

view [ 1 40  3  4]


In [56]:
vr = np.array([[1,2], [3,4]])
vr1= np.array([[9,8],[7,6]])
ar_new = np.concatenate ((vr, vr1),axis=1)
print (vr)
print()
print (vr1)
print()
print(ar_new)
print()
arr= np.concatenate ((vr, vr1),axis=0)
print(arr)

[[1 2]
 [3 4]]

[[9 8]
 [7 6]]

[[1 2 9 8]
 [3 4 7 6]]

[[1 2]
 [3 4]
 [9 8]
 [7 6]]


In [58]:
import numpy as np
var =np.array([1,2,3,4,5,6])
print(var)
ar = np.array_split(var, 3)
print()
print(ar)
print(ar[0])

[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]


In [59]:
var1 = np.array([[1,2], [3,4],[5,6]])
print(var)
ar1= np.array_split(var1,3)
print()
print(ar1)

[1 2 3 4 5 6]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]


In [60]:
import numpy as np
var = np.array([1,2,3,4,2,5,2,5,6,7])
x= np.where( var == 2)
print(x)

(array([1, 4, 6], dtype=int64),)


In [63]:
import numpy as np
var = np.array([1,2,3,4,2,5,2,5,6,7])
x= np.searchsorted(var,5)
print(x)
print(np.sort(var))

5
[1 2 2 2 3 4 5 5 6 7]


In [64]:
import numpy as np
var = np.array([1,2,3,4,2,5,2,5,6,7])
x= np.insert(var, 3, 69)
print(x)
x= np.insert(var, (6,7) , 114)
print(x)

[ 1  2  3 69  4  2  5  2  5  6  7]
[  1   2   3   4   2   5 114   2 114   5   6   7]


In [69]:
import numpy as np

x=np.matrix([[1,2], [3,4],[5,6]])
print(np.transpose(x))
print(x.T)

[[1 3 5]
 [2 4 6]]
[[1 3 5]
 [2 4 6]]


In [74]:
arr=np.matrix([[1,2],[3,4]])
print(np.linalg.inv(arr))
print(np.linalg.matrix_power(arr,0))
print(np.linalg.matrix_power(arr,2))
print(np.linalg.matrix_power(arr,-2))
print(np.linalg.det(arr))

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1 0]
 [0 1]]
[[ 7 10]
 [15 22]]
[[ 5.5  -2.5 ]
 [-3.75  1.75]]
-2.0000000000000004


In [1]:
import numpy as np
 
# Initial Array
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
print("Initial Array: ")
print(arr)
 
# Printing a range of Array
# with the use of slicing method
sliced_arr = arr[:2, ::2]
print ("Array with first 2 rows and"
    " alternate columns(0 and 2):\n", sliced_arr)
 
# Printing elements at
# specific Indices
Index_arr = arr[[1, 1, 0, 3], 
                [3, 2, 1, 0]]
print ("\nElements at indices (1, 3), "
    "(1, 2), (0, 1), (3, 0):\n", Index_arr)

Initial Array: 
[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]
Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (1, 3), (1, 2), (0, 1), (3, 0):
 [0. 6. 2. 3.]
