NumPy is a powerful Python library designed for numerical computations. It is widely used in data science, scientific computing, and machine learning due to its efficiency in handling large datasets and its support for multidimensional arrays. Below are detailed notes about NumPy:

### 1. **What is NumPy?**
   - **NumPy** stands for **Numerical Python**.
   - It provides support for working with **ndarrays** (N-dimensional arrays), which allow for efficient storage and manipulation of large datasets.
   - In addition to arrays, NumPy includes a range of mathematical functions and tools for working with domains like **linear algebra**, **Fourier transforms**, and **random number generation**.

### 2. **Why Use NumPy?**
   - **Efficiency**: NumPy arrays (ndarrays) are much faster than Python lists, especially when performing mathematical operations or processing large datasets.
   - **Optimized for Speed**: Arrays are stored in **contiguous memory locations**, which allows for better CPU caching and faster access (locality of reference).
   - **Rich Functionality**: NumPy comes with a vast array of built-in functions for operations on arrays, such as reshaping, broadcasting, and mathematical operations.
   - **Multidimensional Arrays**: NumPy is not limited to 1D arrays but supports arrays with multiple dimensions, which are essential for data science tasks, such as image processing and matrix computations.

### 3. **Why is NumPy Faster than Python Lists?**
   - **Contiguous Memory Allocation**: Unlike Python lists, which are dynamically resized and can be stored in non-contiguous memory, NumPy arrays are allocated in continuous memory blocks, improving cache performance.
   - **Vectorized Operations**: NumPy can perform operations on entire arrays at once, without needing explicit loops (vectorization). This takes advantage of **SIMD (Single Instruction, Multiple Data)** instructions, making it much faster.
   - **Data Type Uniformity**: Each NumPy array has a specific data type, making memory management and computational overhead lower compared to lists, where each element could have a different data type.

### 4. **NumPy vs Python Lists**:
   - **Size**: NumPy arrays consume less memory than lists, as lists store data along with type information and pointers.
   - **Speed**: Operations like addition, multiplication, or broadcasting are significantly faster with NumPy arrays.
   - **Functionality**: NumPy supports advanced operations such as **matrix multiplication**, **transpositions**, and **linear algebra** out of the box, while Python lists would require additional libraries or manual implementation.

### 5. **Important Concepts in NumPy**:
   - **ndarray (N-dimensional array)**: The core object in NumPy, supporting efficient storage and manipulation of large datasets. It can be of any dimensionality (e.g., 1D, 2D, or higher).
   - **Shape and Dimensions**: Every ndarray has a shape, which defines how many elements are in each dimension (e.g., rows and columns in a 2D array).
   - **Broadcasting**: NumPy supports broadcasting, which allows operations on arrays of different shapes, expanding smaller arrays so they can be combined with larger ones.
   - **Universal Functions (ufuncs)**: These are functions that perform element-wise operations on ndarrays. Examples include `np.add()`, `np.multiply()`, and `np.exp()`.

### 6. **NumPy Ecosystem**:
   - **Integration**: NumPy is at the core of many other scientific libraries, including **pandas** (for data manipulation), **SciPy** (for scientific computations), and **matplotlib** (for data visualization).
   - **Data Science and Machine Learning**: NumPy arrays are often the primary data structure used in frameworks like **TensorFlow**, **scikit-learn**, and **PyTorch** for building machine learning models.

### 7. **Memory Efficiency**:
   - **Fixed Data Types**: Each element in a NumPy array must be of the same data type (e.g., float, int), which allows NumPy to allocate memory efficiently and ensures uniformity.
   - **Data Buffering**: Since NumPy arrays are stored contiguously, they support efficient buffering, making mathematical operations highly optimized.

### 8. **Cross-Language Efficiency**:
   - **Written in C/C++**: Although NumPy is primarily a Python library, many of its computationally heavy operations are implemented in **C** and **C++**, enabling it to harness the low-level speed of these languages.
   - **Interfacing**: NumPy arrays can interface with C, C++, and Fortran, making it a bridge for integrating Python with high-performance code.

### 9. **Application Areas**:
   - **Data Science**: Handling large datasets for statistical analysis and machine learning tasks.
   - **Engineering and Scientific Computing**: Solving complex mathematical problems like partial differential equations or simulations that require heavy matrix operations.
   - **Computer Graphics**: Representing images as 2D or 3D arrays and applying transformations like scaling, rotating, or filtering.

### 10. **Additional Important Points**:
   - **Random Numbers**: NumPy includes modules for generating random numbers, useful for simulations or initializing weights in machine learning models.
   - **Fourier Transforms**: Used for signal processing, NumPy supports fast Fourier transforms (FFT) for frequency analysis.
   - **Linear Algebra**: Built-in functions for matrix multiplication, eigenvalues, and solving linear systems of equations.

In summary, NumPy is essential for efficient numerical and matrix-based operations in Python, providing performance close to low-level languages like C while maintaining the simplicity and ease of Python.

- Size of NumPy array is fixed at creation, unlike Python lists which can grow dynamically.
- Changing the size of an ndarray will create a new array and delete the original one.
- Elements in a NumPy array are required to be of the same data type and have the same size in memory.
- NumPy facilitates advanced mathematical operations, which are executed more efficiently with less code compared to Python’s in-built sequences.

In [3]:
import numpy as np

In [5]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [6]:
print(a)

[1 2 3]


In [7]:
type(a)

numpy.ndarray

In [8]:
print(type(a))

<class 'numpy.ndarray'>


In [13]:
b = np.array([[1,2,3], [4,5,6]]) # 2D NUMPY ARRAY
b 

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
print(b)

[[1 2 3]
 [4 5 6]]


In [15]:
type(b)

numpy.ndarray

In [16]:
print(type(b))

<class 'numpy.ndarray'>


In [20]:
c = np.array([[[1,2],[3,4]], [[5,6],[7,8]]]) #3D VECTOR ALSO CALLED TENSOR
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [24]:
# WE CAN ALSO CREATE NUMPY ARRAY OF SAME DATATYPE CAN BE OF ANYHTING (OBJECT)
arr = np.array([1,2,3], dtype=float)
arr

array([1., 2., 3.])

In [25]:
arr = np.array([1,2,3], dtype=complex)
arr

array([1.+0.j, 2.+0.j, 3.+0.j])

In [26]:
# NP.ARANGE
arr2 = np.arange(1, 11)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr3 = np.arange(1, 11, 2)
arr3

array([1, 3, 5, 7, 9])

In [28]:
arr4 = np.arange(1, 11).reshape(5,2)
arr4

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [29]:
arr4 = np.arange(1, 11).reshape(2,5)
arr4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [30]:
arr4 = np.arange(1, 11).reshape(3, 3)
arr4

ValueError: cannot reshape array of size 10 into shape (3,3)

In [31]:
arr4 = np.arange(1, 11).reshape(3, 4)
arr4

ValueError: cannot reshape array of size 10 into shape (3,4)

In [32]:
# FOR RESHAPING K ELEMENTS WE CAN ONLY DO .RESHAPE(M, N) OR .RESHAPE(N, M) WHERE *****(M*N = K)*****

In [33]:
np.arange(1, 13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
np.arange(1, 13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [35]:
np.arange(1, 13).reshape(12, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [36]:
np.arange(1, 13).reshape(1, 12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [60]:
np.arange(1, 17).reshape(2,2,2,2)

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [61]:
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [62]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [63]:
np.ones((5, 1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [64]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [65]:
np.random.random((3, 4)) # GENERATES RANDOM NUMBERS BETWEEN 0 AND 1

array([[0.47139972, 0.77293708, 0.29892982, 0.12513534],
       [0.84605495, 0.64897033, 0.02690087, 0.09017074],
       [0.47610825, 0.6644368 , 0.78757561, 0.88021961]])

In [66]:
np.random.randint(20, 80, size=(3, 4))

array([[28, 22, 47, 74],
       [52, 58, 36, 57],
       [69, 54, 58, 26]])

`np.linspace()` is a function in NumPy that generates **evenly spaced numbers** over a specified interval.

### Syntax:
```python
np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
```

### Parameters:
- **start**: The starting value of the sequence.
- **stop**: The end value of the sequence.
- **num**: The number of samples to generate (default is 50).
- **endpoint**: If `True`, the stop value is included in the sequence (default is `True`).
- **retstep**: If `True`, it returns the step size between values in addition to the array.
- **dtype**: The data type of the output array (optional).

### Example:
```python
np.linspace(0, 10, 5)
```

This will generate an array with 5 evenly spaced numbers between `0` and `10`:

```
array([ 0. ,  2.5,  5. ,  7.5, 10. ])
```

If `endpoint=False`, the stop value is excluded:

```python
np.linspace(0, 10, 5, endpoint=False)
```

This generates:

```
array([0., 2., 4., 6., 8.])
```

In summary, `np.linspace()` is useful for creating evenly spaced ranges of numbers, which is commonly used in plotting or mathematical computations.

In [67]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [68]:
np.linspace(-10, 10, 10, dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [69]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [70]:
idty = np.identity(4)
print(idty)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**ARRAY ATTRIBUTES**

In [72]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [77]:
#NDIM RETURN DIMENTION OF AN NUMPY ARRAY
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [76]:
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [78]:
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [79]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


In [81]:
a2.astype(np.int32)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [82]:
# scalar operations also possible in numpy arrays

In [83]:
print(2*a1)

[ 0  2  4  6  8 10 12 14 16 18]


In [84]:
print(a1 ** 2)

[ 0  1  4  9 16 25 36 49 64 81]


In [85]:
print(a2 > 5)

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]


In [86]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])

result = a1 + a2
print(result)

[5 7 9]


In [87]:
print(a1 * a2)

[ 4 10 18]


In [101]:
arr = np.random.randint(1, 20, size=(2, 3))
arr

array([[ 8, 18,  1],
       [ 5, 14,  9]])

In [102]:
print(np.max(arr))
print(np.min(arr))
print(np.sum(arr))
print(np.mean(arr))
print(np.prod(arr))

18
1
55
9.166666666666666
90720


In [105]:
print(np.max(arr, axis = 0)) # IT WILL PRINT MINIMUM IN EACH COLUMN

[ 8 18  9]


In [106]:
print(np.max(arr, axis = 1)) # IT WILL PRINT MINIMUM IN EACH ROW

[18 14]


In [107]:
# O->COLUMN ANS 1->ROW

In [108]:
print(np.mean(arr, axis = 1)) # IT WILL PRINT Mean IN EACH ROW

[9.         9.33333333]


In [109]:
print(np.var(arr, axis = 1)) # IT WILL PRINT Variance IN EACH ROW

[48.66666667 13.55555556]


In [110]:
a1 = np.arange(12).reshape(3, 4)
a2 = np.arange(12).reshape(4, 3)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [113]:
a3 = np.dot(a1, a2) # (3, 4) X (4, 3) GIVES (3, 3)
print(a3)

[[ 42  48  54]
 [114 136 158]
 [186 224 262]]


In [126]:
a3 = np.matmul(a1, a2) # (3, 4) X (4, 3) GIVES (3, 3)
print(a3)

[[ 42  48  54]
 [114 136 158]
 [186 224 262]]


In [129]:
# Dot product of two vectors
a = np.array([1, 2])
b = np.array([3, 4])
result = np.dot(a, b)  # Returns 1*3 + 2*4 = 11

# Matrix multiplication of two matrices
c = np.array([[1, 2], [3, 4]])
d = np.array([[5, 6], [7, 8]])
# |1, 2|   |5, 6|
# |3, 4|   |7, 8|
result = np.dot(c, d)  # Same as np.matmul for 2D arrays
print(result)

[[19 22]
 [43 50]]


In [130]:
nmp = np.random.random((2, 3))*100
print(nmp)

[[31.73851796 40.8125083  39.83334035]
 [22.63839216 96.07951918 15.43588633]]


In [131]:
np.round(nmp)

array([[32., 41., 40.],
       [23., 96., 15.]])

In [132]:
np.floor(nmp)

array([[31., 40., 39.],
       [22., 96., 15.]])

In [133]:
np.ceil(nmp)

array([[32., 41., 40.],
       [23., 97., 16.]])

In [135]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
print(a1)
print(a2)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [137]:
print(a1[4])
print(a1[2:9])
print(a1[2:])
print(a1[:4])
print(a1[-1])
print(a1[2:9:2])

4
[2 3 4 5 6 7 8]
[2 3 4 5 6 7 8 9]
[0 1 2 3]
9
[2 4 6 8]


In [142]:
print(a2[2,3]) # 0 based indexing for matrices

11


In [144]:
a3 = np.arange(8).reshape(2,2,2)
print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [145]:
print(a3[0, 1, 1])
print(a3[1, 0, 0])
print(a3[1, 1, 0])

3
4
6


In [146]:
# SLICING IN 2D

In [147]:
a2 = np.arange(12).reshape(3,4)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [148]:
print(a2[0, :])

[0 1 2 3]


In [149]:
print(a2[2, :])

[ 8  9 10 11]


In [150]:
print(a2[1:3, :])

[[ 4  5  6  7]
 [ 8  9 10 11]]


In [151]:
print(a2[:, :])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [153]:
print(a2[:, 1:])

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


In [154]:
print(a2[:, 2])

[ 2  6 10]


In [161]:
print(a2[ ::2, ::3]) # :: IS USED TO TAKE JUMPS STARING FROM 0 ALSO JUMP JUST LIKE SKIPING INCLUDING 0

[[ 0  3]
 [ 8 11]]


In [167]:
print(a2[ ::2, 1:4:2]) # FROM ROWS SKIOPING WITH 2 DIST(ALTERNATE) INCLUDING 0 SKIP AND IN COLUMNS STARING FROM 1 TO 4TH(EXCLUDING IDX) WITH 2 JUMP

[[ 1  3]
 [ 9 11]]


In [168]:
a3 = np.arange(27).reshape(3,3,3)
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [169]:
print(a3[1,0,2])
print(a3[:,1,0])
print(a3[2,:,:])
print(a3[1:,1:,1:])

11
[ 3 12 21]
[[18 19 20]
 [21 22 23]
 [24 25 26]]
[[[13 14]
  [16 17]]

 [[22 23]
  [25 26]]]


In [170]:
print(a3[:,1,:])

[[ 3  4  5]
 [12 13 14]
 [21 22 23]]


**ITERATING ON NUMPY ARRAY**

In [172]:
a1 = np.arange(12)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [174]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [175]:
for i in a1:
    if i%2:
        print(i)
    else:
        print(i+1)

1
1
3
3
5
5
7
7
9
9
11
11


In [177]:
a2 = np.arange(12).reshape(3,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [178]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [181]:
for i in a2:
    for j in i:
        print(j)
    print("---")

0
1
2
3
---
4
5
6
7
---
8
9
10
11
---


In [183]:
for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [184]:
a3 = np.arange(27).reshape(3,3,3)
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [186]:
# "nditer" prints indvisual items from array of any dimension
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


**Reshaping**
    -1.*reshape*
    -2.*transpose*
    -3.*ravel*

In [188]:
a2 = np.arange(12).reshape(3,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [189]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [190]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [191]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [192]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [193]:
print(a2.ravel())
print(a3.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


1. **Horizontal stacking** (`np.hstack`):
   - Joins arrays along their horizontal axis (column-wise).
   - The arrays must have the same number of row]
   ```

2. **Vertical stacking** (`np.vstack`):
   - Joins arrays along their vertical axis (row-wise).
   - The arrays must have the same numbe 2], [3, 4]]
   ```

In [201]:
a = np.arange(6).reshape(2, 3)
b = np.arange(6).reshape(2, 3)
print(a)
print(b)
result = np.hstack((a, b)) 
print(result)
print(result.shape)

[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]]
[[0 1 2 0 1 2]
 [3 4 5 3 4 5]]
(2, 6)


In [202]:
a = np.arange(6).reshape(2, 3)
b = np.arange(6).reshape(2, 3)
print(a)
print(b)
result = np.vstack((a, b)) 
print(result)
print(result.shape)

[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]
 [0 1 2]
 [3 4 5]]
(4, 3)


In [204]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
c = np.array([[13, 14, 15], [16, 17, 18]])
d = np.array([[19, 20, 21], [22, 23, 24]])

result = np.hstack((a, b, c, d))
print(result)
print(result.shape)

[[ 1  2  3  7  8  9 13 14 15 19 20 21]
 [ 4  5  6 10 11 12 16 17 18 22 23 24]]
(2, 12)


In NumPy, you can split arrays horizontally and vertically using `np.hsplit` (horizontal split) and `np.vsplit` (vertical split). Here's how it works:

### **Horizontal Splitting** (`np.hsplit`):
- Splits an array along the horizontal axis (column-wise).
- The array must have columns divisible by the number of splits.

### **Vertical Splitting** (`np.vsplit`):
- Splits an array along the vertical axis (row-wise).
- The array must have rows divisible by the number of splits.

These functions help you divide arrays into equal sub-arrays along the specified axis.

In [211]:
a = np.array([[1, 2, 3, 4, 5, 6], 
              [7, 8, 9, 10, 11, 12]])

result = np.hsplit(a, 3)  # Split into 3 equal parts vertically stack ka just ulta
result

[array([[1, 2],
        [7, 8]]),
 array([[ 3,  4],
        [ 9, 10]]),
 array([[ 5,  6],
        [11, 12]])]

In [212]:
a = np.array([[1, 2, 3, 4], 
              [5, 6, 7, 8], 
              [9, 10, 11, 12], 
              [13, 14, 15, 16]])

result = np.vsplit(a, 2)  # Split into 2 equal parts horizontally stack ka just ulta
result

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]