In [1]:
import numpy as np
a = np.random.randint(1, 100, 15)
a

array([33, 48, 85, 68, 56, 78, 94,  3, 46, 18, 16, 34, 59, 62, 30])

In [2]:
np.sort(a)

array([ 3, 16, 18, 30, 33, 34, 46, 48, 56, 59, 62, 68, 78, 85, 94])

In [7]:
b = np.random.randint(1, 100, 24).reshape(6, 4)
b

array([[98, 94, 49, 32],
       [12, 66, 92, 61],
       [69, 90, 60, 37],
       [19, 66, 69, 46],
       [82, 29,  7, 19],
       [85, 31, 56, 68]])

In [8]:
np.sort(b) #ITS ROW-WISE SORTING IN EACH ROW

array([[32, 49, 94, 98],
       [12, 61, 66, 92],
       [37, 60, 69, 90],
       [19, 46, 66, 69],
       [ 7, 19, 29, 82],
       [31, 56, 68, 85]])

In [6]:
np.sort(b, axis = 0)

array([[19, 28, 24,  7],
       [42, 38, 24, 15],
       [50, 44, 25, 72],
       [70, 47, 33, 74],
       [76, 62, 37, 83],
       [90, 93, 77, 89]])

In [12]:
np.sort(a)[::-1] # FOR REVERSE SORT

array([94, 85, 78, 68, 62, 59, 56, 48, 46, 34, 33, 30, 18, 16,  3])

In [13]:
np.sort(b)[::-1]

array([[31, 56, 68, 85],
       [ 7, 19, 29, 82],
       [19, 46, 66, 69],
       [37, 60, 69, 90],
       [12, 61, 66, 92],
       [32, 49, 94, 98]])

In [19]:
np.append(2387, a) #append at start

array([2387,   33,   48,   85,   68,   56,   78,   94,    3,   46,   18,
         16,   34,   59,   62,   30])

In [20]:
np.append(a, 83865) #append at end

array([   33,    48,    85,    68,    56,    78,    94,     3,    46,
          18,    16,    34,    59,    62,    30, 83865])

In [27]:
# TO ADD 1 AT THE END OF EACH ROW 
toadd = np.ones((b.shape[0], 1))
np.append(b, toadd, axis = 1)

array([[98., 94., 49., 32.,  1.],
       [12., 66., 92., 61.,  1.],
       [69., 90., 60., 37.,  1.],
       [19., 66., 69., 46.,  1.],
       [82., 29.,  7., 19.,  1.],
       [85., 31., 56., 68.,  1.]])

In [28]:
# TO ADD random AT THE END OF EACH ROW 
toadd = np.random.random((b.shape[0], 1))
np.append(b, toadd, axis = 1)

array([[98.        , 94.        , 49.        , 32.        ,  0.11343641],
       [12.        , 66.        , 92.        , 61.        ,  0.0991471 ],
       [69.        , 90.        , 60.        , 37.        ,  0.3429672 ],
       [19.        , 66.        , 69.        , 46.        ,  0.4098459 ],
       [82.        , 29.        ,  7.        , 19.        ,  0.75295128],
       [85.        , 31.        , 56.        , 68.        ,  0.32411505]])

# ***NP.CONCATENATE***

In [31]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)
# print(np.concatenate(c, d)) # provid arrays to concatenate inside a tuple
np.concatenate((c, d))

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [33]:
np.concatenate((c, d), axis = 0) #its by default

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [34]:
np.concatenate((c, d), axis = 1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [35]:
e = np.array([1,1,2,2,2,3,4,4,4,4,4,5,6,7])
np.unique(e)

array([1, 2, 3, 4, 5, 6, 7])

# ***np.expand_dims***
:- is used to add a new axis to an array, effectively increasing the dimensionality of the array. The key idea is that it allows reshaping data without changing its values, just adding an extra dimension to the array's shape.

### How it works:
- **Input:** A NumPy array of any shape.
- **Functionality:** You specify the axis (position in the shape) where you want to add a new dimension.
- **Output:** A new array with the same data, but one additional dimension.

### Example:
For a 1D array with shape `(3,)`, applying `np.expand_dims(arr, axis=0)` changes the shape to `(1, 3)` by adding a new dimension at position 0. Similarly, you can add dimensions anywhere along the array.

This function is often used in operations like broadcasting or aligning dimensions for matrix operations.

In [43]:
arr_1d = np.array([1, 2, 3])
arr_2d = np.expand_dims(arr_1d, axis=0)  # Adds a new axis at position 0 (rows)
print(arr_2d)

[[1 2 3]]


In [44]:
arr_1d = np.array([1, 2, 3])
arr_2d = np.expand_dims(arr_1d, axis=1)  # Adds a new axis at position 1 (cols)
print(arr_2d)

[[1]
 [2]
 [3]]


In [45]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_3d = np.expand_dims(arr_2d, axis=0)  # Adds a new axis at position 0
print(arr_3d)

[[[1 2 3]
  [4 5 6]]]


In [46]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_3d = np.expand_dims(arr_2d, axis=1)  # Adds a new axis at position 1
print(arr_3d)

[[[1 2 3]]

 [[4 5 6]]]


In [47]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]]])
arr_4d = np.expand_dims(arr_3d, axis=0)  # Adds a new axis at position 0
print(arr_4d)

[[[[1 2 3]
   [4 5 6]]]]


In [48]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]]])
arr_4d = np.expand_dims(arr_3d, axis=1)  # Adds a new axis at position 1
print(arr_4d)

[[[[1 2 3]
   [4 5 6]]]]


# ***np.where*** 
:- is a versatile function in NumPy that allows conditional selection of elements from arrays. It's primarily used for three key tasks: selecting elements based on conditions, finding the indices of elements that satisfy a condition, and performing element-wise operations.

### Syntax:
```python
np.where(condition, [x, y])
```

### How it works:
1. **Condition-based Selection:**
   - **Input:** A condition (typically a boolean array or expression) and two optional arrays `x` and `y`.
   - **Output:** If the condition is `True`, it selects from `x`; if `False`, it selects from `y`.

   Example:
   ```python
   arr = np.array([1, 2, 3, 4, 5])
   result = np.where(arr > 3, arr, 0)
   # Output: array([0, 0, 0, 4, 5])
   ```
   This replaces values where the condition `arr > 3` is not satisfied with `0`.

2. **Finding Indices:**
   - **Input:** Only the condition.
   - **Output:** Returns the indices where the condition is `True`.

   Example:
   ```python
   indices = np.where(arr > 3)
   # Output: (array([3, 4]),)
   ```

### Use Cases:
- **Conditional selection of values** (like an element-wise "if-else").
- **Indexing for data extraction** based on a condition.
- **Masking or replacing values in arrays** based on specific conditions.



In [56]:
arr = np.random.randint(1, 10, 7)
print(arr)
indices = np.where(arr > 3)
print(indices) 

[6 6 2 1 9 1 6]
(array([0, 1, 4, 6], dtype=int64),)


# ***based on condition we can replce values within given array***

In [57]:
np.where(arr > 3, arr, -1) # based on condition we can replce values within given array

array([ 6,  6, -1, -1,  9, -1,  6])

In [60]:
a = np.array([11, 53, 28, 50, 38, 37, 61, 72, 5, 30, 64, 9, 82, 2, 211])
result2 = np.where(a % 2 == 0, 'even', 'odd')
print(result2)

['odd' 'odd' 'even' 'even' 'even' 'odd' 'odd' 'even' 'odd' 'even' 'even'
 'odd' 'even' 'even' 'odd']


# np.argmax

In [62]:
arr_1d = np.array([10, 20, 15, 30, 25])
max_index_1d = np.argmax(arr_1d)
print(max_index_1d)  # Output: 3 (index of 30)

3


In [64]:
arr_2d = np.array([[10, 50, 30], [60, 20, 90], [70, 80, 40]])
max_index_2d = np.argmax(arr_2d, axis = 0)
print(max_index_2d)  

[2 2 1]


In [65]:
arr_2d = np.array([[10, 50, 30], [60, 20, 90], [70, 80, 40]])
max_index_2d = np.argmax(arr_2d, axis = 1)
print(max_index_2d)  

[1 2 1]


In [71]:
a = np.random.randint(1,100,15)
print(a)
print(np.percentile(a,50)) # median
print(np.percentile(a,100)) # max
print(np.percentile(a,0)) # min

[54 20 89 25 79 97 34 70 71 42 51 84 49 71  1]
54.0
97.0
1.0


In [69]:
np.median(a)

57.0

In [74]:
np.histogram(a,bins=[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]) 
# it prints how many numbers are there between 0-10, 10-20, 20-30 .... 90-100

(array([1, 0, 2, 1, 2, 2, 0, 4, 2, 1], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

### `numpy.isin()` Method

- **Purpose:** Checks if elements of one array are present in another array or list.
- **Syntax:** 
  ```python
  numpy.isin(target_array, list)
  ```
- **Returns:** A boolean array with the same size as `target_array`, where each element indicates whether it is present in `list`.

In [76]:
items = [10,20,30,40,50,60,70,80,90]
print(items)
print(a)
np.isin(a, items)

[10, 20, 30, 40, 50, 60, 70, 80, 90]
[54 20 89 25 79 97 34 70 71 42 51 84 49 71  1]


array([False,  True, False, False, False, False, False,  True, False,
       False, False, False, False, False, False])

In [77]:
a

array([54, 20, 89, 25, 79, 97, 34, 70, 71, 42, 51, 84, 49, 71,  1])

In [78]:
np.flip(a)

array([ 1, 71, 49, 84, 51, 42, 71, 70, 34, 97, 79, 25, 89, 20, 54])

In [79]:
b

array([[98, 94, 49, 32],
       [12, 66, 92, 61],
       [69, 90, 60, 37],
       [19, 66, 69, 46],
       [82, 29,  7, 19],
       [85, 31, 56, 68]])

In [81]:
np.flip(b) # flip on both row and column

array([[68, 56, 31, 85],
       [19,  7, 29, 82],
       [46, 69, 66, 19],
       [37, 60, 90, 69],
       [61, 92, 66, 12],
       [32, 49, 94, 98]])

In [82]:
b

array([[98, 94, 49, 32],
       [12, 66, 92, 61],
       [69, 90, 60, 37],
       [19, 66, 69, 46],
       [82, 29,  7, 19],
       [85, 31, 56, 68]])

In [83]:
np.flip(b, axis = 0)

array([[85, 31, 56, 68],
       [82, 29,  7, 19],
       [19, 66, 69, 46],
       [69, 90, 60, 37],
       [12, 66, 92, 61],
       [98, 94, 49, 32]])

In [84]:
np.flip(b, axis = 1)

array([[32, 49, 94, 98],
       [61, 92, 66, 12],
       [37, 60, 90, 69],
       [46, 69, 66, 19],
       [19,  7, 29, 82],
       [68, 56, 31, 85]])

In [85]:
a

array([54, 20, 89, 25, 79, 97, 34, 70, 71, 42, 51, 84, 49, 71,  1])

In [86]:
np.delete(a, 0)

array([20, 89, 25, 79, 97, 34, 70, 71, 42, 51, 84, 49, 71,  1])

In [88]:
np.delete(a, 5) # 97 from original a will be deleted

array([54, 20, 89, 25, 79, 34, 70, 71, 42, 51, 84, 49, 71,  1])

# set operations which returns numpy array

In [90]:
m = np.array([1, 2, 3, 4, 5])
n = np.array([3, 4, 5, 6, 7])

# np.union1d - Union of two arrays
union = np.union1d(m, n)
print("Union:", union)

# np.intersect1d - Intersection of two arrays
intersection = np.intersect1d(m, n)
print("Intersection:", intersection)

# np.setdiff1d - Set difference (elements in m but not in n)
set_difference = np.setdiff1d(m, n)
print("Set Difference (m - n):", set_difference)

# np.setxor1d - Set symmetric difference (elements in either m or n but not in both)
set_xor = np.setxor1d(m, n)
print("Set XOR:", set_xor)

# np.in1d - Check if elements of m are in n (returns boolean array)
in1d_result = np.in1d(m, n)
print("Elements of m in n:", in1d_result)

Union: [1 2 3 4 5 6 7]
Intersection: [3 4 5]
Set Difference (m - n): [1 2]
Set XOR: [1 2 6 7]
Elements of m in n: [False False  True  True  True]


# np.clip which sets higher and lower limit in an numpoy array

In [91]:
a

array([54, 20, 89, 25, 79, 97, 34, 70, 71, 42, 51, 84, 49, 71,  1])

In [92]:
np.clip(a, 25, 75)

array([54, 25, 75, 25, 75, 75, 34, 70, 71, 42, 51, 75, 49, 71, 25])